import { Driver, RideOrder, PricingConfig, User } from './types';

export const mockAdmin: User = {
  id: 'admin-1',
  name: 'Admin TukTuk',
  email: 'admin@tuktuk.co.ke',
  phone: '+254700000000',
  role: 'admin',
  createdAt: '2024-01-01',
};

export const mockClient: User = {
  id: 'client-1',
  name: 'Sydney Achieng',
  email: 'sydney@example.com',
  phone: '+254712345678',
  role: 'client',
  createdAt: '2024-06-15',
};

export const mockDrivers: Driver[] = [
  {
    id: 'driver-1',
    name: 'James Ochieng',
    email: 'james@tuktuk.co.ke',
    phone: '+254711111111',
    role: 'driver',
    vehicle: 'Bajaj RE',
    licensePlate: 'KBA 123A',
    rating: 4.8,
    totalTrips: 342,
    earnings: 145600,
    online: true,
    suspended: false,
    createdAt: '2024-03-10',
    documents: [
      { id: 'd1', type: 'license', name: 'Driving License', status: 'approved', uploadedAt: '2024-03-10' },
      { id: 'd2', type: 'insurance', name: 'Vehicle Insurance', status: 'approved', uploadedAt: '2024-03-10' },
      { id: 'd3', type: 'vehicle_registration', name: 'Vehicle Registration', status: 'approved', uploadedAt: '2024-03-10' },
      { id: 'd4', type: 'good_conduct', name: 'Good Conduct Certificate', status: 'pending', uploadedAt: '2024-03-12' },
    ],
  },
  {
    id: 'driver-2',
    name: 'Peter Kamau',
    email: 'peter@tuktuk.co.ke',
    phone: '+254722222222',
    role: 'driver',
    vehicle: 'TVS King',
    licensePlate: 'KCA 456B',
    rating: 4.5,
    totalTrips: 198,
    earnings: 89200,
    online: false,
    suspended: false,
    createdAt: '2024-04-20',
    documents: [
      { id: 'd5', type: 'license', name: 'Driving License', status: 'approved', uploadedAt: '2024-04-20' },
      { id: 'd6', type: 'insurance', name: 'Vehicle Insurance', status: 'rejected', uploadedAt: '2024-04-20' },
    ],
  },
  {
    id: 'driver-3',
    name: 'Mary Wanjiku',
    email: 'mary@tuktuk.co.ke',
    phone: '+254733333333',
    role: 'driver',
    vehicle: 'Piaggio Ape',
    licensePlate: 'KDA 789C',
    rating: 4.9,
    totalTrips: 521,
    earnings: 234500,
    online: true,
    suspended: false,
    createdAt: '2024-02-01',
    documents: [
      { id: 'd7', type: 'license', name: 'Driving License', status: 'approved', uploadedAt: '2024-02-01' },
      { id: 'd8', type: 'insurance', name: 'Vehicle Insurance', status: 'approved', uploadedAt: '2024-02-01' },
      { id: 'd9', type: 'vehicle_registration', name: 'Vehicle Registration', status: 'approved', uploadedAt: '2024-02-01' },
      { id: 'd10', type: 'good_conduct', name: 'Good Conduct Certificate', status: 'approved', uploadedAt: '2024-02-05' },
    ],
  },
];

export const mockOrders: RideOrder[] = [
  {
    id: 'order-1',
    clientId: 'client-1',
    clientName: 'Sydney Achieng',
    driverId: 'driver-1',
    driverName: 'James Ochieng',
    pickup: 'Westlands, Nairobi',
    dropoff: 'CBD, Nairobi',
    status: 'completed',
    fare: 350,
    paymentMethod: 'mpesa',
    distance: '5.2 km',
    duration: '18 min',
    createdAt: '2024-12-01T10:30:00',
  },
  {
    id: 'order-2',
    clientId: 'client-1',
    clientName: 'Sydney Achieng',
    driverId: 'driver-3',
    driverName: 'Mary Wanjiku',
    pickup: 'Kilimani, Nairobi',
    dropoff: 'Ngong Road, Nairobi',
    status: 'completed',
    fare: 250,
    paymentMethod: 'cash',
    distance: '3.1 km',
    duration: '12 min',
    createdAt: '2024-12-02T14:15:00',
  },
  {
    id: 'order-3',
    clientId: 'client-1',
    clientName: 'Sydney Achieng',
    pickup: 'Karen, Nairobi',
    dropoff: 'Langata, Nairobi',
    status: 'pending',
    fare: 400,
    paymentMethod: 'mpesa',
    distance: '7.8 km',
    duration: '25 min',
    createdAt: '2024-12-05T08:00:00',
  },
];

export const mockPricing: PricingConfig = {
  baseFare: 100,
  perKm: 40,
  perMinute: 5,
  minimumFare: 150,
  surgePricing: 1.0,
};

export const mockClients: User[] = [
  mockClient,
  {
    id: 'client-2',
    name: 'Faith Njeri',
    email: 'faith@example.com',
    phone: '+254744444444',
    role: 'client',
    suspended: false,
    createdAt: '2024-07-20',
  },
  {
    id: 'client-3',
    name: 'Brian Kipchoge',
    email: 'brian@example.com',
    phone: '+254755555555',
    role: 'client',
    suspended: true,
    createdAt: '2024-08-05',
  },
];
